### ISSUE TITLE
gulp-favicons not working in gulp workflow

### ISSUE THREAD

**Issue by stalinkay** [haydenbleasel/favicons#122]
I installed **gulp-favicons** as part of my gulp workflow but it crashes when this I use `favicons = require('gulp-favicon');` even without running the task, it still produces the following error

```
/Volumes/SK Repo 1.0/Projects/Stalin Kay/Web Development/htdocs/namcor/mockup/node_modules/gulp-favicons/index.js:3
(() => {
  ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Volumes/SK Repo 1.0/Projects/Stalin Kay/Web Development/htdocs/namcor/mockup/gulpfile.js:6:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by stalinkay** [comment]
Please disregard this. I forgot to check the dependencies.
