### ISSUE TITLE
Unexpected token '='

### ISSUE THREAD

**Issue by alexdrans** [haydenbleasel/favicons#152]
Hey,

Currently having an issue with ``favicons-webpack-plugin`` via  the ``favicons`` package.

Here's my error;

```
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\...\node_modules\favicons-webpack-plugin\node_modules\favicons\helpers-es5.js:18:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\...\node_modules\favicons-webpack-plugin\node_modules\favicons\es5.js:11:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\...\node_modules\favicons-webpack-plugin\lib\favicons.js:3:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at DependenciesBlock.loadPitch (...\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:193:17)
    at DependenciesBlock.doBuild (...\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:241:4)
```

However, I can't see why it's happening, as ``helpers-es5.js:18`` is [this line](https://github.com/haydenbleasel/favicons/blob/master/helpers-es5.js#L18)

```
var path = require('path'),
    fs = require('fs'),
    _ = require('underscore'),
    color = require('tinycolor2'),
    cheerio = require('cheerio'),
    colors = require('colors'),
    jsonxml = require('jsontoxml'),
    sizeOf = require('image-size'),
    async = require('async'),
    mkdirp = require('mkdirp'),
    Jimp = require('jimp'),
    svg2png = require('svg2png'),
    File = require('vinyl'),
    Reflect = require('harmony-reflect'),
    NRC = require('node-rest-client').Client,
    PLATFORM_OPTIONS = require('./config/platform-options.json');
```

I can't build on Windows, or Heroku, but OS X seems to build fine.

**Comment by haydenbleasel** [comment]
Hey @alexdrans, what version of Node are you running?

**Comment by alexdrans** [comment]
v4.5.0

**Comment by haydenbleasel** [comment]
If you're running the ES6 version (likely) then you should probably be jumping on Node 5 or 6+

**Comment by alexdrans** [comment]
Thanks for the rapid reply. Let me check whether v6.5.0 fixes it!

**Comment by alexdrans** [comment]
Yep, all working! 🎈 Thanks @haydenbleasel. Awesome module also.

**Comment by haydenbleasel** [comment]
@alexdrans No worries homie 👍

**Comment by crisu83** [comment]
@haydenbleasel this is still an issue in projects that use e.g. favicons-webpack-plugin and cannot upgrade to Node 6.x. Don't you have any plans to support older versions of Node than 6?

**Comment by haydenbleasel** [comment]
@crisu83 If you read our docs, we compile an ES5 version of Favicons. All you need to change in Webpack Favicons is require('favicons') to require('favicons/es5').

However, Node 0.10 is only maintained until October and 0.12 until December. I suggest upgrading to v4 or v6.

**Comment by crisu83** [comment]
@haydenbeasel I did read your docs, but I encounted this issue on Node 4.x.

**Comment by santo74** [comment]
I'm using favicons in my Ember.js app via the ember-cli-favicon addon and am experiencing the same issue. Everything worked fine with Node v4.3.1 until my last commit from 2 days ago.
That commit didn't change anything regarding versions, it only contained some simple modifications in an ember template and some extra rules in a less stylesheet.

Switching to Node 6 is currently not an option. I especially stick with Node 4 as that is the current, supported LTS version of Node.
Moreover, everything worked fine with this setup until my last commit, so I think it's not directly related to the version of Node.

Note: I had similar issues in the past, where the cause was apparently an es5 compilation issue: [https://github.com/haydenbleasel/favicons/issues/147](https://github.com/haydenbleasel/favicons/issues/147)

**Comment by santo74** [comment]
FYI: ember-cli-favicons relies on broccoli-favicons, which in turn relies on the favicons library.
As you can see in the code, the broccoli-favicons library already uses the es5 version: [https://github.com/davewasmer/broccoli-favicon/blob/master/index.js](https://github.com/davewasmer/broccoli-favicon/blob/master/index.js)

**Comment by santo74** [comment]
Fixed by pull request [https://github.com/haydenbleasel/favicons/pull/154](https://github.com/haydenbleasel/favicons/pull/154)
